version: '3.7'
services:
  sajadv-db:
    image: sajadv-db
    ports:
      - "5432:5432"
    networks:
      - app-net
    build:
      context: sajadv-db/
    restart: unless-stopped
  sajadv-eureka-server:
    image: sajadv-eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-net
    build:
      context: sajadv-eureka-server/
    restart: unless-stopped
  sajadv-api:
    image: sajadv-api
    depends_on:
      - sajadv-db
      - sajadv-eureka-server
    ports:
      - "8080:8080"
    networks:
      - app-net
    build:
      context: sajadv-api/
    restart: unless-stopped
  sajadv-app:
    image: sajadv-app
    depends_on:
      - sajadv-api
    ports:
      - "4200:80"
    networks:
      - app-net
    build:
      context: sajadv-app/
    restart: unless-stopped
volumes:
  postgres-data:
networks:
  app-net: