server:
  servlet:
    context-path: /sajadv-service/v1

spring:
  profiles:
    active: postgres
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sajadv
    username: sajadv
    password: s4j@dv2020