server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuizPauloS/sajadv/sajadv-config
          #uri: file://home/luiz/Documentos/Projetos/java/desafios/sajadv/sajadv-config/src/main/resources/
          #clone-on-start: true