server:
  servlet:
    context-path: /sajadv-persons-api/v1

spring:
  cloud:
    config:
      uri: https://github.com/LuizPauloS/sajadv-configs
      password: 55caadd2cdadcd188f86b87250789af379a77142